SHAYERI = [
    "Teri aankhon mein hai kaisa ye nasha,\nTu hi hai meri zindagi ki akhiri aasha.",
    "Tujhe dekhne ki rehti hai hamesha pyaas,\nTu hi hai mere dil ke sabse zyada paas.",
    "Har pal tujhe hi mangne ki hai ye aas,\nTere bina lagti hai har khushi udaas.",
    "Zindagi mein chahiye bas tera hi saath,\nTham kar rakhna hamesha mera ye haath.",
    "Tere chehre par rehta hai alag hi noor,\nTujhse milne ko dil hota hai majboor.",
    "Dil mein basayi hai teri haseen tasveer,\nTu hi hai mere hathon ki sabse pyari lakeer.",
    "Tujhse milkar mil gaya jeene ka bahana,\nAb tere bin mushkil hai ye dil lagana.",
    "Teri baaton mein hai kaisa ye jaadu,\nAb nahi rehta mera mere dil par kaabu.",
    "Tu mile toh milti hai dil ko rahat,\nTu hi hai meri sabse badi chahat.",
    "Teri muskurahat par dil ye marta hai,\nTujhe khone se ye pal-pal darta hai.",
    "Tujhse door jana hai sabse badi saza,\nTere saath jeene mein hai alag hi maza.",
    "Tu hai mere liye sabse zyada khaas,\nIsliye rehti hai tu dil ke itne paas.",
    "Har dua mein mangte hain teri hi salaamti,\nTu hi hai mere khwabon ki pyari kainaati.",
    "Teri saadgi ne kar diya mujhe pagal,\nTu hi hai mere banjar dil ka badal.",
    "Teri har ada mein chhippa hai ek raaz,\nSunta hoon dil se teri hi awaaz.",
    "Mohabbat mein teri hum kuch is qadar kho gaye,\nTujhe dekhte hi hum tere ho gaye.",
    "Bas ek baar dekh kar muskura diya karo,\nMere saare dukhon ko pal mein mita diya karo.",
    "Tu hai mere har dard ki dawai,\nTere bina duniya lagti hai parayi.",
    "Teri dosti hai meri sabse badi shaan,\nTujh par nisaar hai meri ye jaan.",
    "Zindagi ki raahon mein chahiye tera sahara,\nTu hi hai mere dubte dil ka kinara.",
    "Tera naam likh kar main muskurata hoon,\nTujhe yaad karke har gham bhulata hoon.",
    "Tere ishq ka rang mujh par aisa chadh gaya,\nKe mera har rasta teri taraf badh gaya.",
    "Khuda se mangi hai bas teri hi wafa,\nKabhi mat hona mujhse tum khafa.",
    "Teri har baat mein ek mehak hai,\nJaise mere baag mein koyi chehak hai.",
    "Tujhe pana hi meri zindagi ka hai maqsad,\nTu hi hai meri har khushi ka be-had.",
    "Dil ki har dhadkan mein tera hi naam hai,\nTu hi meri subah aur tu hi meri shaam hai.",
    "Tere bina ye duniya lagti hai adhoori,\nTujhse milna ab ban gaya hai zaroori.",
    "Teri ek jhalak hi kafi hai sukoon ke liye,\nTujhe chahenge hum agle kayi joon ke liye.",
    "Mohabbat hai tumse ye baat bata di hai,\nMaine apni duniya tere naam saja di hai.",
    "Tera saath hai toh har mushkil asaan hai,\nTu hi meri zindagi aur tu hi meri jaan hai.",
    "Tere honton ki wo pyari si hansi,\nMere dil mein jaise bijli si phansi.",
    "Tu hai mere liye ek haseen tohfa,\nKabhi na dena mujhe tum dhokha.",
    "Teri aankhon ke sagar mein doob jana hai,\nAb mujhe tere hi dil mein thikana banana hai.",
    "Har mausam mein teri hi mehak aaye,\nJab bhi tu hanse mera dil behak jaye.",
    "Tujh par marta hoon ye mera ikraar hai,\nZindagi mein sirf tujhse hi pyaar hai.",
    "Tu hai mere khwabon ki malika,\nSeekha hai maine tujhse ishq ka tarika.",
    "Tere intezar mein hai alag hi nasha,\nTu hi hai meri har uljhan ki dasha.",
    "Bas tere paas rehne ki hai ek aarzoo,\nHamesha rahe mere samne bas tu hi tu.",
    "Zindagi ki dhoop mein tu hai thandi chhaon,\nTere bina lage sunsan mera poora gaon.",
    "Teri dosti mein mile hain haseen tohfe,\nAb nahi chahiye duniya ke koi bhi mauke.",
    "Tujhe dekh kar dil ko aata hai qaraar,\nKitna karun main tera aur intezaar.",
    "Tere ishq mein hum badnaam ho gaye,\nTere dar par aake gulam ho gaye.",
    "Tu hai wo phool jo kabhi murjhata nahi,\nTujhsa pyaara koi nazar aata nahi.",
    "Har saans mein tera hi ehsas hai,\nLagta hai jaise tu har pal mere paas hai.",
    "Mohabbat ki rahon mein tera hi saath mangte hain,\nHum toh bas teri hi mulaqat mangte hain.",
    "Teri har muskurahat par hai jaan nisaar,\nTujhse karta hoon sacha aur be-had pyaar.",
    "Tu hai mere dil ka sacha karar,\nTujh par luta doon main ye poora sansar.",
    "Tere bina dil nahi lagta mera,\nHar taraf dikhta hai bas chehra tera.",
    "Tu hai meri zindagi ki sabse haseen subah,\nTujh bin adhoori hai meri har ek wajah.",
    "Teri baaton mein hai kaisa ye mithaas,\nTu hi hai meri sabse pyari ehsas.",
    "Aankhon mein khwab aur dil mein tu hai,\nHar jagah bas teri hi guftagu hai.",
    "Tu hai wo chand jis par sab fida hain,\nPar tu sirf meri sabse pyari ada hai.",
    "Teri galiyon mein hi guzre mera din,\nJee nahi sakta main ab tere bin.",
    "Zindagi ki har khushi tujhse judi hai,\nMeri har dua tere dar par mudi hai.",
    "Tu hai meri har shayari ka unwan,\nTere liye hazar baar haazir hai meri jaan.",
    "Teri aankhon mein hai kaisa ye surma,\nKar diya tune mere dil ko hai kurma.",
    "Tu mile toh mil jaye poori kainaat,\nKash hamesha ho hamari yun hi baat.",
    "Tere ishq ne banaya hai mujhe itna haseen,\nAb lagta hai tujh par hi hai mera yakeen.",
    "Teri har ada par main fida hoon,\nTujhse milne ke liye main sada hoon.",
    "Tu hi hai meri zindagi ki pehli aur aakhiri aarzoo,\nJahan dekhun wahan dikhe bas tu hi tu.",
    "Tera saath ho toh maut bhi manzoor hai,\nKyunki tu hi mere jeene ka fitoor hai.",
    "Teri har hansi mein hai ek gehra raaz,\nSabse alag hai teri ye awaaz.",
    "Mohabbat ki rahon mein kabhi mat chhodna saath,\nHamesha thame rehna mera ye pyara haath.",
    "Tere bina zindagi lagti hai ek bojh,\nTujhe milne ki karta hoon koshish har roz.",
    "Tu hai mere dil ka sabse keemti gehna,\nSada mere dil ke kareeb hi rehna.",
    "Teri har nazar mein hai kaisa ye teer,\nBadal di tune mere hathon ki taqdeer.",
    "Tu hai mere liye sabse bada inaam,\nTere hi naam se shuru ho meri har shaam.",
    "Teri dosti par hai mujhe pura naaz,\nTu hi hai mere dil ka sacha saaz.",
    "Tujhse door ho kar lagta hai darr,\nTu hi hai mere dil ka asli ghar.",
    "Teri muskan hai meri asli kamai,\nTere bina duniya lagti hai ek khai.",
    "Tu mile toh mil jaye dil ko sukoon,\nTere ishq mein hai kaisa ye junoon.",
    "Teri aankhon mein duba rehna chahta hoon,\nSari umar tera ban kar rehna chahta hoon.",
    "Tu hai wo sitara jo kabhi toot-ta nahi,\nTera saath mujhse kabhi chhoot-ta nahi.",
    "Har pal tera hi intezar rehta hai,\nYe dil sirf tujh par hi marta hai.",
    "Teri har baat mein hai ek naya andaaz,\nTu hi hai mere khwabon ka parwaaz.",
    "Tu hai mere jivan ki sabse badi umeed,\nTujhe dekh kar hi milti hai mujhe eid.",
    "Teri har ada mein hai kaisa ye kamaal,\nKar diya tune mere dil ka bura haal.",
    "Tujhse milkar badal gayi meri duniya,\nTu hi hai meri sabse pyaari gudiya.",
    "Teri har saans mein meri hi dhadkan ho,\nHum dono ka saath hamesha janmon-janman ho.",
    "Tu hai mere liye khuda ka ek roop,\nThandi chhaon mein hai tu pyari si dhoop.",
    "Teri dosti ne sikhaya hai jeena,\nTere bina mushkil hai gham ka zeher peena.",
    "Tu hai wo khwab jo pura ho gaya,\nTujhe pate hi main sab kuch kho gaya.",
    "Teri aankhon ki chamak mein hai kaisa ye nasha,\nTu hi hai meri har khushi ki disha.",
    "Tu hai mere dil ka sabse bada raaz,\nSabse haseen hai tera ye andaaz.",
    "Teri har hansi par main kurbaan jaun,\nTujhe dekhte hi main khud ko bhool jaun.",
    "Zindagi mein bas tera hi saath ho,\nHamesha hamare sir par tera hi haath ho.",
    "Tu hai mere liye sabse haseen khwaab,\nTere bina zindagi lagti hai be-hisaab.",
    "Teri har baat mein hai kaisa ye asar,\nTujhse hi roshan hai mera ye safar.",
    "Tu mile toh mil jaye dil ka qaraar,\nKitna karun main tera aur intezaar.",
    "Teri muskurahat hai meri zindagi ka noor,\nTujhse door rehna hai humein na-manzoor.",
    "Tu hai wo phool jiski mehak hai sabse alag,\nTu hi hai meri aankhon ki pyari si palak.",
    "Teri har nazar mein hai ek naya payam,\nTere hi naam se ho meri har ek shaam.",
    "Tu hai meri har dua ka sacha asar,\nTere bina adhoora hai mera ye safar.",
    "Teri dosti mein hai kaisa ye nasha,\nTu hi hai meri zindagi ki sahi disha.",
    "Tu mile toh mil jaye khushi ka khazana,\nAb tere bin mushkil hai dil ka lagana.",
    "Teri har baat par mujhe yakeen hai,\nTu is duniya mein sabse haseen hai.",
    "Tu hai mere dil ka sacha sahara,\nTere bina adhoora hai mera ye guzara.",
    "Teri aankhon mein hai kaisa ye jadu,\nNahi rehta ab mere dil par mera kabu.",
    "Tu hai meri zindagi ki sabse pyari umeed,\nTujhe dekh kar hi milti hai mujhe asli eid.",
    "Teri har ada par hai ye dil fida,\nKabhi mat hona mere khuda mujhse juda.",
    "Tujhe dekh kar chehre pe aa jati hai chamak,\nTere bina har khushi lagti hai be-namak.",
    "Teri dosti hai mere liye sabse pyari,\nTu hi hai meri zindagi ki sabse badi tyari.",
    "Tujhse milna hi meri sabse badi mannat hai,\nTu saath ho toh har jagah jannat hai.",
    "Tere bina ye dil chain se reh nahi pata,\nApne dil ki baat kisi se keh nahi pata.",
    "Tu hai wo baarish jo sukoon lati hai,\nTeri yaad har pal mujhse milne aati hai.",
    "Tujh par luta doon main ye saari duniya,\nTu hi hai meri sabse sundar gudiya.",
    "Tere ishq mein hum deewane ho gaye,\nTujhe paane ke liye zamane ho gaye.",
    "Tu hai mere dil ki sabse pyari dhadkan,\nTere bina lagta hai sab kuch ek bandhan.",
    "Teri har baat par mujhe garv hota hai,\nTere saath har lamha ek parv hota hai.",
    "Tujhse door hona meri maut ke barabar hai,\nTu hi mere har dard ka asli asar hai.",
    "Teri ek muskan se milta hai dil ko karar,\nKitna karta hoon main tujhse saccha pyar.",
    "Tu hai mere liye sabse bada samman,\nTere bina adhoora hai mera ye jahan.",
    "Teri aankhon mein hai meri saari kainaat,\nKash hamesha bani rahe hamari ye baat.",
    "Tu hai mere liye ek anmol ratan,\nTujhe khone ka kabhi na karunga jatan.",
    "Teri har muskurahat par dil fida hai,\nTu hi mere har marz ki pyari dawa hai.",
    "Tujhse milkar badal gayi meri ye kismat,\nTu hi hai meri sabse badi haseen nemat.",
    "Tere bin har din lagta hai ek saal,\nTu hi hai mere dil ka asli khayal.",
    "Tu hai mere liye sabse haseen tohfa,\nKabhi na hona mujhse tum kabhi khafa.",
    "Teri dosti mein hai kaisa ye nasha,\nTu hi hai meri zindagi ki sahi disha.",
    "Tujh par marti hai meri har ek saans,\nTu hi hai meri sabse pyari aur khaas.",
    "Teri har ada mein hai ek alag hi baat,\nHamesha chahiye mujhe tera hi saath.",
    "Tu hai mere liye ek pyaara sa sapna,\nAb tujhe hi banana hai mujhe apna.",
    "Teri aankhon ki gehrai mein kho gaya hoon,\nTujhse milte hi tera sacha premi ho gaya hoon.",
    "Tu hai mere dil ki sabse pyari raani,\nTere bina adhoori hai meri ye kahani.",
    "Teri har muskurahat par hai meri jaan,\nTu hi hai mere dil ka sacha armaan.",
    "Tu mile toh mil jaye dil ko sukoon,\nTere ishq mein hai kaisa ye pagalpan aur junoon.",
    "Teri dosti mein hai kaisa ye sukoon,\nTu hi hai mere dil ka asli junoon.",
    "Tujh par fida hai meri har ek ada,\nKabhi mat hona mere sanam mujhse juda.",
    "Teri har muskan par dil kurban hai,\nTu hi meri zindagi aur tu hi meri jaan hai.",
    "Tu hai mere liye sabse haseen nagma,\nTujh bin adhoora hai mera har ek sapna.",
    "Teri aankhon ke noor se hai meri duniya roshan,\nTu hi hai mere dil ka sabse haseen gulshan.",
    "Tu hai meri har shayari ka mukhya unwan,\nTere liye hazar baar haazir hai meri jaan.",
    "Teri har hansi mein hai ek naya andaaz,\nSabse alag hai teri ye haseen awaaz.",
    "Mohabbat ki rahon mein tera hi saath mangte hain,\nHum toh bas teri hi ek mulaqat mangte hain.",
    "Tu hai meri har dua ka sacha sa asar,\nTere bina adhoora hai mera ye lamba safar.",
    "Teri har nazar mein hai kaisa ye teer,\nBadal di tune mere khali hathon ki taqdeer.",
    "Tu hai mere liye sabse bada inaam,\nTere hi naam se shuru ho meri har haseen shaam.",
    "Teri dosti par hai mujhe sacha sa naaz,\nTu hi hai mere khwabon ka sacha parwaaz.",
    "Tujhse door ho kar lagta hai har pal darr,\nTu hi hai mere dil ka asli aur pakka ghar.",
    "Teri muskan hai meri asli aur sachi kamai,\nTere bina duniya lagti hai mujhe ek khai.",
    "Tu mile toh mil jaye dil ko asli sukoon,\nTere ishq mein hai kaisa ye pyara junoon.",
    "Teri aankhon mein duba rehna chahta hoon,\nSari umar bas tera hi ban kar rehna chahta hoon.",
    "Tu hai wo sitara jo kabhi bhi toot-ta nahi,\nTera saath mujhse kabhi bhi chhoot-ta nahi.",
    "Har pal tera hi sacha intezar rehta hai,\nYe dil sirf tujh par hi har baar marta hai.",
    "Teri har baat mein hai ek naya andaaz,\nTu hi hai mere khwabon ka sacha parwaaz.",
    "Tu hai mere jivan ki sabse badi aur sachi umeed,\nTujhe dekh kar hi milti hai mujhe asli eid.",
    "Teri har ada mein hai kaisa ye sacha kamaal,\nKar diya tune mere dil ka bahut bura haal.",
    "Tujhse milkar badal gayi meri ye chhoti duniya,\nTu hi hai meri sabse pyaari aur sundar gudiya.",
    "Teri har saans mein meri hi sachi dhadkan ho,\nHum dono ka saath hamesha janmon-janman ho.",
    "Tu hai mere liye khuda ka ek sacha roop,\nThandi chhaon mein hai tu pyari si aur meethi dhoop.",
    "Teri dosti ne sikhaya hai mujhe asli jeena,\nTere bina mushkil hai gham ka kadwa zeher peena.",
    "Tu hai wo khwab jo ab pura ho gaya,\nTujhe pate hi main apna sab kuch kho gaya.",
    "Teri aankhon ki chamak mein hai kaisa ye nasha,\nTu hi hai meri har khushi ki sahi disha.",
    "Tu hai mere dil ka sabse bada aur pyara raaz,\nSabse haseen hai tera ye sacha andaaz.",
    "Teri har hansi par main sacha kurbaan jaun,\nTujhe dekhte hi main khud ko poora bhool jaun.",
    "Zindagi mein bas tera hi sacha saath ho,\nHamesha hamare sir par tera hi pyara haath ho.",
    "Tu hai mere liye sabse haseen aur sacha khwaab,\nTere bina zindagi lagti hai mujhe be-hisaab.",
    "Teri har baat mein hai kaisa ye sacha asar,\nTujhse hi roshan hai mera ye zindagi ka safar.",
    "Tu mile toh mil jaye dil ka sacha qaraar,\nKitna karun main tera aur sacha intezaar.",
    "Teri muskurahat hai meri zindagi ka asli noor,\nTujhse door rehna hai ab humein na-manzoor.",
    "Tu hai wo phool jiski mehak hai sabse alag,\nTu hi hai meri aankhon ki pyari si aur sachi palak.",
    "Teri har nazar mein hai ek naya payam,\nTere hi naam se ho meri har ek haseen shaam.",
    "Tu hai meri har dua ka sacha sa asar,\nTere bina adhoora hai mera ye zindagi ka safar.",
    "Teri dosti mein hai kaisa ye sacha nasha,\nTu hi hai meri zindagi ki ekdam sahi disha.",
    "Tu mile toh mil jaye khushi ka asli khazana,\nAb tere bin mushkil hai dil ka sacha lagana.",
    "Teri har baat par mujhe poora yakeen hai,\nTu is poori duniya mein sabse zyada haseen hai.",
    "Tu hai mere dil ka ek sacha sahara,\nTere bina adhoora hai mera ye har guzara.",
    "Teri aankhon mein hai kaisa ye sacha jadu,\nNahi rehta ab mere dil par mera sacha kabu.",
    "Tu hai meri zindagi ki sabse pyari aur sachi umeed,\nTujhe dekh kar hi milti hai mujhe asli aur meethi eid.",
    "Teri har ada par hai ye mera dil fida,\nKabhi mat hona mere khuda mujhse kabhi juda.",
    "Teri muskurahat se milti hai dil ko thandak,\nTere bina har khushi lagti hai mujhe mandak.",
    "Tu hai meri har ek saans ki pyari wajah,\nTere bina jeena hai mere liye ek badi saza.",
    "Tujhse juda rehna ab namumkin lagta hai,\nTere bina ye dil bahut zyada thagta hai.",
    "Tu hai mere khwabon ka ek pyara sa sheher,\nTere ishq ka mujh par hua hai sacha asar.",
    "Teri har baat mere dil ko chhu jati hai,\nTeri yaad mujhe har pal bahut satati hai.",
    "Tujh par luta doon main apni ye saari jaan,\nTu hi hai meri sachi aur pyari pehchan.",
    "Tere ishq mein main sab kuch bhula baitha hoon,\nTere dil mein apni choti si duniya basa baitha hoon.",
    "Tu hai mere liye ek sacha aur pyara farishta,\nTujhse juda hai mera ye sabse anmol rishta.",
    "Teri har nazar mein hai ek sacha sa pyar,\nKitna karun main tera aur sacha intezar.",
    "Tu hai mere dil ki sabse pyari aur sachi rani,\nTere bina adhoori hai meri ye sachi kahani.",
    "Teri har muskurahat par hai meri sachi jaan,\nTu hi hai mere dil ka sacha aur pyara armaan.",
    "Tu mile toh mil jaye dil ko asli sukoon,\nTere ishq mein hai kaisa ye pagalpan aur junoon.",
    "Teri dosti mein hai kaisa ye sacha sukoon,\nTu hi hai mere dil ka asli aur pyara junoon.",
    "Tujh par fida hai meri har ek sachi ada,\nKabhi mat hona mere sanam mujhse kabhi juda.",
    "Teri har muskan par dil sacha kurban hai,\nTu hi meri zindagi aur tu hi meri sachi jaan hai.",
    "Tu hai mere liye sabse haseen aur sacha nagma,\nTujh bin adhoora hai mera har ek pyara sapna.",
    "Teri aankhon ke noor se hai meri duniya roshan,\nTu hi hai mere dil ka sabse haseen aur pyara gulshan.",
    "Tu hai meri har shayari ka mukhya aur sacha unwan,\nTere liye hazar baar haazir hai meri sachi jaan.",
    "Teri har hansi mein hai ek naya aur sacha andaaz,\nSabse alag hai teri ye haseen aur sachi awaaz.",
    "Mohabbat ki rahon mein tera hi sacha saath mangte hain,\nHum toh bas teri hi ek sachi mulaqat mangte hain.",
    "Tu hai meri har dua ka sacha aur pyara asar,\nTere bina adhoora hai mera ye zindagi ka safar.",
    "Teri har nazar mein hai kaisa ye sacha teer,\nBadal di tune mere khali hathon ki pyari taqdeer.",
    "Tu hai mere liye sabse bada aur pyara inaam,\nTere hi naam se shuru ho meri har haseen shaam.",
    "Teri dosti par hai mujhe sacha aur poora naaz,\nTu hi hai mere khwabon ka sacha aur pyara parwaaz.",
    "Tujhse door ho kar lagta hai har pal sacha darr,\nTu hi hai mere dil ka asli aur pakka pyara ghar.",
    "Teri muskan hai meri asli aur sachi sachi kamai,\nTere bina duniya lagti hai mujhe ek gehri khai.",
    "Tu mile toh mil jaye dil ko asli aur pyara sukoon,\nTere ishq mein hai kaisa ye sacha aur pyara junoon.",
    "Teri aankhon mein duba rehna chahta hoon,\nSari umar bas tera hi ban kar rehna chahta hoon.",
    "Tu hai wo sitara jo kabhi bhi toot-ta nahi,\nTera saath mujhse kabhi bhi chhoot-ta nahi.",
    "Har pal tera hi sacha aur pyara intezar rehta hai,\nYe dil sirf tujh par hi har baar sacha marta hai.",
    "Teri har baat mein hai ek naya aur sacha andaaz,\nTu hi hai mere khwabon ka sacha aur pyara parwaaz.",
    "Tu hai mere jivan ki sabse badi aur sachi umeed,\nTujhe dekh kar hi milti hai mujhe asli aur meethi eid.",
    "Teri har ada mein hai kaisa ye sacha aur pyara kamaal,\nKar diya tune mere dil ka bahut bura aur bura haal.",
    "Tujhse milkar badal gayi meri ye chhoti si duniya,\nTu hi hai meri sabse pyaari aur sundar sachi gudiya.",
    "Teri har saans mein meri hi sachi aur pyari dhadkan ho,\nHum dono ka saath hamesha janmon-janman tak ho.",
    "Tu hai mere liye khuda ka ek sacha aur pyara roop,\nThandi chhaon mein hai tu pyari si aur meethi dhoop.",
    "Teri dosti ne sikhaya hai mujhe asli aur sacha jeena,\nTere bina mushkil hai gham ka kadwa zeher peena.",
    "Tu hai wo khwab jo ab mera poora ho gaya,\nTujhe pate hi main apna sab kuch sacha kho gaya.",
    "Teri aankhon ki chamak mein hai kaisa ye sacha nasha,\nTu hi hai meri har khushi ki ekdam sahi disha.",
    "Tu hai mere dil ka sabse bada aur pyara sacha raaz,\nSabse haseen hai tera ye sacha aur pyara andaaz.",
    "Teri har hansi par main sacha aur poora kurbaan jaun,\nTujhe dekhte hi main khud ko poora aur sacha bhool jaun.",
    "Zindagi mein bas tera hi sacha aur pyara saath ho,\nHamesha hamare sir par tera hi pyara aur sacha haath ho.",
    "Tu hai mere liye sabse haseen aur sacha sa khwaab,\nTere bina zindagi lagti hai mujhe ekdam be-hisaab.",
    "Teri har baat mein hai kaisa ye sacha aur sacha asar,\nTujhse hi roshan hai mera ye zindagi ka pyara safar.",
    "Tu mile toh mil jaye dil ka sacha aur pyara qaraar,\nKitna karun main tera aur sacha aur sacha intezaar.",
    "Teri muskurahat hai meri zindagi ka asli aur sacha noor,\nTujhse door rehna hai ab humein bilkul na-manzoor.",
    "Tu hai wo phool jiski mehak hai sabse alag aur pyaari,\nTu hi hai meri aankhon ki pyari si aur sachi palak saari.",
    "Teri har nazar mein hai ek naya aur sacha payam,\nTere hi naam se ho meri har ek haseen aur sachi shaam.",
    "Tu hai meri har dua ka sacha aur pyara sa asar,\nTere bi
